server:
  port: 18005
spring:
  application:
    name: wisdomschool-monitor-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    #类型
    content-type: text/html
    #文件后缀
    suffix: .ftl
    #路径
    template-loader-path: classpath:/templates/
    settings:
      classic_compatible: true
